rootUrl: https://alexpts.ru
tolerance: 3.5
screenshotsDir: './screens'

system:
  parallelLimit: 2
  plugins:
    browserstack:
      username: false
      accessKey: false

browsers:
  chrome:
    desiredCapabilities:
      acceptSslCerts: true
      browserName: chrome
      platform: WIN8
      os: WINDOWS
      os_version: 8.1
      project: alexpts.ru_css
      resolution: 1280x800

  ie10:
    desiredCapabilities:
      acceptSslCerts: true
      browserName: IE
      browser: IE
      browser_version: 10
      platform: WIN8
      os: WINDOWS
      os_version: 8
      project: alexpts.ru_css
      resolution: 1280x800

  ie11:
    desiredCapabilities:
      acceptSslCerts: true
      browserName: IE
      browser: IE
      browser_version: 11
      platform: WIN8
      os: WINDOWS
      os_version: 8.1
      project: alexpts.ru_css
      resolution: 1280x800

sets:
  alexpts.ru:
    files:
      - ./test/