rootUrl: https://alexpts.ru
tolerance: 3.5
screenshotsDir: './screens'

httpTimeout: 5000
sessionRequestTimeout: 10000
sessionQuitTimeout: 5000

#system:
#  parallelLimit: 2
#  plugins:
#    browserstack:
#      username: xxx
#      accessKey: xxx

browsers:
  chrome:
    desiredCapabilities:
      acceptSslCerts: true
      browserName: chrome
      platform: WIN8
      os: WINDOWS
      os_version: 8.1
      project: alexpts.ru_css
      resolution: 1280x800
      chromeOptions:
        args:
          - '--start-fullscreen'

sets:
  alexpts.ru:
    files:
      - ./test/